spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/local

---
spring:
  config:
    activate:
      on-profile: dev
